version: '2.3'

services:

  blender:
    image: cloudnativecomputer/blender:latest
    shm_size: 6gb
    runtime: nvidia
    restart: always
    labels:
      - traefik.enable=true
      # - traefik.frontend.auth.forward.address=http://traefik-forward-auth:8080
      # - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      # - traefik.frontend.auth.forward.trustForwardHeader=true
      - traefik.frontend.rule=Host:blender.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
    volumes:
      - CLOUD_COMPUTER_CLOUDSTORAGE:$CLOUD_COMPUTER_CLOUDSTORAGE
      - CLOUD_COMPUTER_HOME:$CLOUD_COMPUTER_HOME

volumes:
  CLOUD_COMPUTER_CLOUDSTORAGE:
    external: true
  CLOUD_COMPUTER_HOME:
    external: true
