version: '2.3'

services:

  desktop:
    image: sabrehagen/desktop-environment:latest
    command: sleep infinity
    shm_size: 6gb
    restart: always
    environment:
      - DESKTOP_ENVIRONMENT_USER=$CLOUD_COMPUTER_HOST_USER
    security_opt:
      - seccomp:unconfined
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:desktop.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
    volumes:
      - CLOUD_COMPUTER_CLOUDSTORAGE:$CLOUD_COMPUTER_CLOUDSTORAGE
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
      - CLOUD_COMPUTER_TMUX:$CLOUD_COMPUTER_TMUX
      - CLOUD_COMPUTER_X11:$CLOUD_COMPUTER_X11

volumes:
  CLOUD_COMPUTER_CLOUDSTORAGE:
  CLOUD_COMPUTER_REPOSITORY:
  CLOUD_COMPUTER_TMUX:
  CLOUD_COMPUTER_X11:
