version: '2.3'

services:

  desktop:
    image: cloudnativecomputer/desktop:latest
    shm_size: 6gb
    restart: always
    environment:
      - DESKTOP_ENVIRONMENT_USER=$CLOUD_COMPUTER_HOST_USER
      - DISPLAY=:1
    security_opt:
      - seccomp:unconfined
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:desktop.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - CLOUD_COMPUTER_CACHE_CHROME:$CLOUD_COMPUTER_CACHE_CHROME
      - CLOUD_COMPUTER_CACHE_CODE:$CLOUD_COMPUTER_CACHE_CODE
      - CLOUD_COMPUTER_CACHE_TMUX:$CLOUD_COMPUTER_CACHE_TMUX
      - CLOUD_COMPUTER_CACHE_YARN:$CLOUD_COMPUTER_CACHE_YARN
      - CLOUD_COMPUTER_CACHE_ZSH:$CLOUD_COMPUTER_CACHE_ZSH
      - CLOUD_COMPUTER_CLOUDSTORAGE:$CLOUD_COMPUTER_CLOUDSTORAGE
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
      - CLOUD_COMPUTER_STATE_CHROME:$CLOUD_COMPUTER_STATE_CHROME
      - CLOUD_COMPUTER_STATE_CODE:$CLOUD_COMPUTER_STATE_CODE
      - CLOUD_COMPUTER_STATE_I3:$CLOUD_COMPUTER_STATE_I3
      - CLOUD_COMPUTER_STATE_JUMP:$CLOUD_COMPUTER_STATE_JUMP
      - CLOUD_COMPUTER_STATE_SLACK:$CLOUD_COMPUTER_STATE_SLACK
      - CLOUD_COMPUTER_TMUX:$CLOUD_COMPUTER_TMUX

volumes:
  CLOUD_COMPUTER_CACHE_CHROME:
    external: true
  CLOUD_COMPUTER_CACHE_CODE:
    external: true
  CLOUD_COMPUTER_CACHE_TMUX:
    external: true
  CLOUD_COMPUTER_CACHE_YARN:
    external: true
  CLOUD_COMPUTER_CACHE_ZSH:
    external: true
  CLOUD_COMPUTER_CLOUDSTORAGE:
    external: true
  CLOUD_COMPUTER_REPOSITORY:
    external: true
  CLOUD_COMPUTER_STATE_CHROME:
    external: true
  CLOUD_COMPUTER_STATE_CODE:
    external: true
  CLOUD_COMPUTER_STATE_I3:
    external: true
  CLOUD_COMPUTER_STATE_JUMP:
    external: true
  CLOUD_COMPUTER_STATE_SLACK:
    external: true
  CLOUD_COMPUTER_TMUX:
    external: true
