version: '2.3'

services:

  dispatch:
    image: cloudnativecomputer/dispatch:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:irc.$CLOUD_COMPUTER_DNS_NAME
      - traefik.port=8080
