version: '3.5'

services:

  jaeger:
    image: jaegertracing/all-in-one:1.8
    restart: always
    labels:
      namespace: jaeger
      tier: cloud-computer
    labels:
      - traefik.jaeger.enable=true
      - traefik.jaeger.frontend.rule=Host:jaeger.$CLOUD_COMPUTER_DNS_NAME
      - traefik.jaeger.port=16686
      - traefik.jaeger-collector.enable=true
      - traefik.jaeger-collector.frontend.rule=Host:jaeger-collector.$CLOUD_COMPUTER_DNS_NAME
      - traefik.jaeger-collector.port=14268
