version: '3.5'

services:

  marketplace:
    image: cloudnativecomputer/marketplace:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:marketplace.$CLOUD_COMPUTER_DNS_NAME
      - traefik.port=8080
