version: '3.5'

services:

  krita:
    image: cloudnativecomputer/non:latest
    shm_size: 6gb
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:non.$CLOUD_COMPUTER_DNS_NAME,daw.$CLOUD_COMPUTER_DNS_NAME
      - traefik.port=8080
    volumes:
      - CLOUD_COMPUTER_CLOUDSTORAGE:$CLOUD_COMPUTER_CLOUDSTORAGE

volumes:
  CLOUD_COMPUTER_CLOUDSTORAGE:
    external: true
