version: '3.5'

services:

  traefik:
    image: traefik:latest
    command:
      - --api
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.email=jackson@cloud-computer.dev
      - --acme.storage=/var/run/traefik/acme.json
      - --acme.entryPoint=https
      - --acme.onHostRule=true
      - --acme.httpChallenge.entryPoint=http
      - --docker
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.domain=cloud-computer.dev
      - --docker.watch=true
      - --docker.exposedByDefault=false
      - --logLevel=DEBUG
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - CLOUD_COMPUTER_TRAEFIK:/var/run/traefik

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    environment:
      - CLIENT_ID=your-client-id
      - CLIENT_SECRET=your-client-secret
      - OIDC_ISSUER=https://accounts.google.com
      - SECRET=traefik-forward-auth-secret
      - AUTH_HOST=auth.example.com
    labels:
      - traefik.frontend.rule=Host:auth.$CLOUD_COMPUTER_HOST_DNS
      - traefik.frontend.auth.forward.address=http://traefik-forward-auth:8080
      - traefik.frontend.auth.forward.trustForwardHeader=true
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=traefik-forward-auth
      - traefik.redirectorservice.frontend.entryPoints=http
      - traefik.redirectorservice.frontend.redirect.entryPoint=https
      - traefik.webservice.frontend.entryPoints=https

volumes:
  CLOUD_COMPUTER_TRAEFIK:
