version: '3.5'

services:

  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.2
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres/mantra
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
      HASURA_GRAPHQL_CORS_DOMAIN: '*'
      HASURA_GRAPHQL_ADMIN_SECRET: mantra
      HASURA_GRAPHQL_JWT_SECRET: "{\"type\":\"HS256\",\"key\":\"3xQftRWq,~-8g>d&[FjVLJsXDuAYt.w:\"}"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:hasura.webapp.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
    depends_on:
      - postgres
      - mail

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mantra
      POSTGRES_HOST: postgres
      JSON_SECRET: '3xQftRWq,~-8g>d&[FjVLJsXDuAYt.w:'
      GOOGLE_CLIENT_ID: 820336721515-df68p28g744u9cls3m9sipi7fu52or70.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: A2D3oGjc5LgVciktZPl_fof2
      GOOGLE_CALLBACK: https://auth.webapp.$CLOUD_COMPUTER_HOST_DNS/auth/google/callback
      GITHUB_CLIENT_ID: Iv1.33d7572b0ba5c40a
      GITHUB_CLIENT_SECRET: 2c78b2f15715c34647498d1573467bbe1646cf43
      GITHUB_CALLBACK: https://auth.webapp.$CLOUD_COMPUTER_HOST_DNS/auth/github/callback
      REACT_APP: https://client.webapp.$CLOUD_COMPUTER_HOST_DNS
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:auth.webapp.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=3000
    depends_on:
      - postgres

  mail:
    build:
      context: ./mail-service
      dockerfile: Dockerfile
    environment:
      MAIL_SERVICE_DOMAIN: sandbox47f2a5030ace4d899fe52eba517c4551.mailgun.org
      MAIL_SERVICE_APIKEY: f77050361b2c8a1731d4ebc4fe4e6d20-16ffd509-09d514e4
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mantra
