version: '3'

services:

  client:
    image: node:10.16.0-alpine
    command: yarn dev
    working_dir: $CLOUD_COMPUTER_REPOSITORY/apps/webapp/client
    environment:
      AUTH_SERVICE_HOST: $AUTH_SERVICE_HOST
      REACT_APP: $REACT_APP
      REACT_APP_HOST: $REACT_APP_HOST
      REACT_APP_WEBSOCKET_HOST: $REACT_APP_WEBSOCKET_HOST
      STREAM_HOST: $STREAM_HOST
      GOOGLE_CALLBACK: $GOOGLE_CALLBACK
      GOOGLE_REDIRECT: $GOOGLE_REDIRECT
      GITHUB_CALLBACK: $GITHUB_CALLBACK
      GITHUB_REDIRECT: $GITHUB_REDIRECT
    volumes:
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:dev.client.webapp.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=3000

  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.4.cli-migrations
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB
      HASURA_GRAPHQL_ENABLE_CONSOLE: $HASURA_GRAPHQL_ENABLE_CONSOLE
      HASURA_GRAPHQL_ENABLE_TELEMETRY: $HASURA_GRAPHQL_ENABLE_TELEMETRY
      HASURA_GRAPHQL_CORS_DOMAIN: $HASURA_GRAPHQL_CORS_DOMAIN
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_GRAPHQL_ADMIN_SECRET
      HASURA_GRAPHQL_JWT_SECRET: "{\"type\":\"HS256\",\"key\":\"$JSON_SECRET\"}"
      HASURA_GRAPHQL_MIGRATIONS_DIR: $CLOUD_COMPUTER_REPOSITORY/apps/webapp/hasura-console/migrations
    volumes:
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
    depends_on:
      - postgres
      - mail
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:dev.hasura.webapp.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080

  auth:
    image: node:10.16.0-alpine
    command: yarn dev
    working_dir: $CLOUD_COMPUTER_REPOSITORY/apps/webapp/auth-service
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      JSON_SECRET: $JSON_SECRET
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      GOOGLE_CALLBACK: $GOOGLE_CALLBACK
      GITHUB_CLIENT_ID: $GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET
      GITHUB_CALLBACK: $GITHUB_CALLBACK
      REACT_APP: $REACT_APP
    volumes:
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:dev.auth.webapp.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=3000
    depends_on:
      - postgres

  stream:
    image: node:10.16.0-alpine
    command: yarn dev
    working_dir: $CLOUD_COMPUTER_REPOSITORY/apps/webapp/stream-service
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      REDIS_HOST: $REDIS_HOST
    volumes:
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:dev.stream.webapp.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=3000
    depends_on:
      - postgres

  worker:
    image: node:10.16.0-alpine
    command: yarn dev
    working_dir: $CLOUD_COMPUTER_REPOSITORY/apps/webapp/worker-service
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      REDIS_HOST: $REDIS_HOST
    volumes:
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
    depends_on:
      - postgres

  mail:
    image: node:10.16.0-alpine
    command: yarn dev
    working_dir: $CLOUD_COMPUTER_REPOSITORY/apps/webapp/mail-service
    environment:
      MAIL_SERVICE_DOMAIN: $MAIL_SERVICE_DOMAIN
      MAIL_SERVICE_APIKEY: $MAIL_SERVICE_APIKEY
    volumes:
      - CLOUD_COMPUTER_REPOSITORY:$CLOUD_COMPUTER_REPOSITORY
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:dev.mail.webapp.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=3000
    depends_on:
      - postgres

  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

volumes:
  CLOUD_COMPUTER_REPOSITORY:
